# Generated by Django 6.0.7 on 2026-07-16 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('codigo_trabajador', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('antiguedad', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='catalogos.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='catalogos.cargo')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'beneficiarios',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiarioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('elegible', models.BooleanField(default=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='beneficiarios.beneficiario')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Beneficiario del Evento',
                'verbose_name_plural': 'Beneficiarios por Evento',
                'db_table': 'beneficiario_evento',
                'constraints': [models.UniqueConstraint(fields=('beneficiario', 'evento'), name='unique_beneficiario_evento')],
            },
        ),
    ]
