# Generated by Django 6.0.7 on 2026-07-16 16:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
        ('zonas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('tipo_entrega', models.CharField(choices=[('TITULAR', 'Titular'), ('TERCERO', 'Tercero')], default='TITULAR', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('beneficiario_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='beneficiarios.beneficiarioevento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_registradas', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='zonas.zona')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entrega',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='EntregaTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('dni_autorizado', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 dígitos.', regex='^\\d{8}$')])),
                ('nombre_autorizado', models.CharField(max_length=150)),
                ('parentesco', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_entrega', to=settings.AUTH_USER_MODEL)),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tercero', to='entregas.entrega')),
            ],
            options={
                'verbose_name': 'Entrega a tercero',
                'verbose_name_plural': 'Entregas a terceros',
                'db_table': 'entrega_tercero',
            },
        ),
    ]
