# Generated by Django 6.0.3 on 2026-07-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True, verbose_name='Debe cambiar contraseña'),
        ),
    ]
