# Generated by Django 6.0.7 on 2026-07-16 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('accion', models.CharField(help_text='Acción realizada.', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la acción.')),
                ('metodo_http', models.CharField(blank=True, help_text='Método HTTP utilizado.', max_length=10)),
                ('endpoint', models.CharField(blank=True, help_text='Ruta de la API consumida.', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción.', null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
